mainFile = main.cpp
lib1File = Cell.cpp
lib2File = Apple.cpp

build: $(mainFile) $(lib1File) $(lib2File)
	g++ $(mainFile) $(lib1File) $(lib2File) -lsfml-graphics -lsfml-window -lsfml-system -o cellAutomata